export const foodBlogCategories = [
  'Recipes by Cuisine',
  'Meal Types',
  'Dietary Preferences',
  'Cooking Techniques',
  'Seasonal Foods',
  'Quick & Easy',
  'Budget-Friendly Recipes',
  'Healthy Eating',
  'Ingredient-Specific',
  'Festive & Holiday Foods',
  "Kids' Favorites",
  'Food Trends',
  'Restaurant Reviews',
  'Cooking Tips & Tricks',
  'International Street Foods',
];
